CREATE SCHEMA IF NOT EXISTS crm;
CREATE SCHEMA IF NOT EXISTS extensions;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE n.nspname = 'public'
          AND t.typname = 'app_role'
    ) THEN
        CREATE TYPE public.app_role AS ENUM ('owner', 'admin', 'sales', 'viewer');
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.organizations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    owner_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dealer_team_members (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    user_id uuid NOT NULL,
    role public.app_role NOT NULL DEFAULT 'viewer'::public.app_role,
    permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS dealer_team_members_org_user_idx
    ON public.dealer_team_members (organization_id, user_id);

CREATE TABLE IF NOT EXISTS public.admin_users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    username text NOT NULL,
    password_hash text NOT NULL DEFAULT '',
    email text,
    full_name text,
    role text NOT NULL DEFAULT 'admin',
    is_active boolean NOT NULL DEFAULT true,
    last_login_at timestamptz,
    password_changed_at timestamptz NOT NULL DEFAULT now(),
    failed_login_attempts integer NOT NULL DEFAULT 0,
    locked_until timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid,
    password_change_required boolean NOT NULL DEFAULT true
);

CREATE UNIQUE INDEX IF NOT EXISTS admin_users_username_key
    ON public.admin_users (username);

CREATE TABLE IF NOT EXISTS public.admin_sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    admin_user_id uuid NOT NULL REFERENCES public.admin_users(id) ON DELETE CASCADE,
    session_token text NOT NULL,
    expires_at timestamptz NOT NULL,
    ip_address inet,
    user_agent text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_activity_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS admin_sessions_session_token_key
    ON public.admin_sessions (session_token);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    actor_id uuid,
    action text NOT NULL,
    target_resource text,
    details jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_favorites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id text NOT NULL,
    car_id text NOT NULL,
    title text,
    year integer,
    price_won bigint,
    link text,
    image text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.vin_checks (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamptz NOT NULL DEFAULT now(),
    name text NOT NULL,
    whatsapp text NOT NULL,
    vin text NOT NULL,
    status text NOT NULL DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS crm.dealer_users (
    id uuid PRIMARY KEY,
    dealer_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    server_updated_at timestamptz NOT NULL DEFAULT now(),
    last_modified_by uuid,
    first_name text,
    last_name text,
    phone text,
    avatar_url text,
    email text
);

CREATE TABLE IF NOT EXISTS crm.financial_accounts (
    id uuid PRIMARY KEY,
    dealer_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    account_type text NOT NULL DEFAULT 'cash',
    balance numeric NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    server_updated_at timestamptz NOT NULL DEFAULT now(),
    last_modified_by uuid
);

CREATE TABLE IF NOT EXISTS crm.vehicles (
    id uuid PRIMARY KEY,
    dealer_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    vin text NOT NULL,
    make text,
    model text,
    year integer,
    purchase_price numeric NOT NULL DEFAULT 0,
    purchase_date date NOT NULL DEFAULT CURRENT_DATE,
    status text NOT NULL DEFAULT 'on_sale',
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    sale_price numeric,
    sale_date date,
    photo_url text,
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    server_updated_at timestamptz NOT NULL DEFAULT now(),
    last_modified_by uuid,
    asking_price numeric,
    report_url text,
    purchase_account_id uuid REFERENCES crm.financial_accounts(id) ON DELETE SET NULL,
    mileage integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS crm.expense_templates (
    id uuid PRIMARY KEY,
    dealer_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    name text NOT NULL,
    category text NOT NULL DEFAULT 'other',
    default_description text,
    default_amount numeric,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    server_updated_at timestamptz NOT NULL DEFAULT now(),
    last_modified_by uuid
);

CREATE TABLE IF NOT EXISTS crm.expenses (
    id uuid PRIMARY KEY,
    dealer_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    amount numeric NOT NULL DEFAULT 0,
    date date NOT NULL DEFAULT CURRENT_DATE,
    expense_description text,
    category text NOT NULL DEFAULT 'other',
    created_at timestamptz NOT NULL DEFAULT now(),
    vehicle_id uuid REFERENCES crm.vehicles(id) ON DELETE SET NULL,
    user_id uuid REFERENCES crm.dealer_users(id) ON DELETE SET NULL,
    account_id uuid REFERENCES crm.financial_accounts(id) ON DELETE SET NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    server_updated_at timestamptz NOT NULL DEFAULT now(),
    last_modified_by uuid,
    description text,
    receipt_path text,
    expense_type text
);

CREATE TABLE IF NOT EXISTS crm.sales (
    id uuid PRIMARY KEY,
    dealer_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    vehicle_id uuid NOT NULL REFERENCES crm.vehicles(id) ON DELETE CASCADE,
    amount numeric NOT NULL DEFAULT 0,
    date date NOT NULL DEFAULT CURRENT_DATE,
    buyer_name text,
    buyer_phone text,
    payment_method text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    server_updated_at timestamptz NOT NULL DEFAULT now(),
    last_modified_by uuid,
    sale_price numeric,
    profit numeric NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'completed',
    account_id uuid REFERENCES crm.financial_accounts(id) ON DELETE SET NULL,
    notes text,
    vat_refund_percent numeric(5, 2),
    vat_refund_amount numeric(15, 2)
);

CREATE TABLE IF NOT EXISTS crm.dealer_clients (
    id uuid PRIMARY KEY,
    dealer_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    name text NOT NULL,
    phone text,
    email text,
    notes text,
    request_details text,
    preferred_date timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    vehicle_id uuid REFERENCES crm.vehicles(id) ON DELETE SET NULL,
    status text NOT NULL DEFAULT 'new',
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    server_updated_at timestamptz NOT NULL DEFAULT now(),
    last_modified_by uuid
);

CREATE TABLE IF NOT EXISTS crm.account_transactions (
    id uuid PRIMARY KEY,
    dealer_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    account_id uuid NOT NULL REFERENCES crm.financial_accounts(id) ON DELETE CASCADE,
    transaction_type text NOT NULL DEFAULT 'deposit',
    amount numeric NOT NULL DEFAULT 0,
    date timestamptz NOT NULL DEFAULT now(),
    note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    server_updated_at timestamptz NOT NULL DEFAULT now(),
    last_modified_by uuid
);

CREATE TABLE IF NOT EXISTS crm.debts (
    id uuid PRIMARY KEY,
    dealer_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    counterparty_name text NOT NULL,
    counterparty_phone text,
    direction text NOT NULL DEFAULT 'owed_to_me',
    amount numeric NOT NULL DEFAULT 0,
    notes text,
    due_date date,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    server_updated_at timestamptz NOT NULL DEFAULT now(),
    last_modified_by uuid
);

CREATE TABLE IF NOT EXISTS crm.debt_payments (
    id uuid PRIMARY KEY,
    dealer_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    debt_id uuid NOT NULL REFERENCES crm.debts(id) ON DELETE CASCADE,
    amount numeric NOT NULL DEFAULT 0,
    date timestamptz NOT NULL DEFAULT now(),
    note text,
    payment_method text,
    account_id uuid REFERENCES crm.financial_accounts(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    server_updated_at timestamptz NOT NULL DEFAULT now(),
    last_modified_by uuid
);

CREATE TABLE IF NOT EXISTS crm.cars (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    make text NOT NULL DEFAULT '',
    model text NOT NULL DEFAULT '',
    year integer NOT NULL DEFAULT 0,
    price numeric NOT NULL DEFAULT 0,
    mileage numeric NOT NULL DEFAULT 0,
    fuel text NOT NULL DEFAULT '',
    transmission text NOT NULL DEFAULT '',
    image text,
    type text NOT NULL DEFAULT '',
    description text,
    featured boolean NOT NULL DEFAULT false,
    most_wanted boolean NOT NULL DEFAULT false,
    engine text,
    shipping text,
    status text,
    image_version integer
);

CREATE OR REPLACE VIEW public.crm_account_transactions AS
SELECT * FROM crm.account_transactions;

CREATE OR REPLACE VIEW public.crm_dealer_clients AS
SELECT * FROM crm.dealer_clients;

CREATE OR REPLACE VIEW public.crm_dealer_users AS
SELECT * FROM crm.dealer_users;

CREATE OR REPLACE VIEW public.crm_debt_payments AS
SELECT * FROM crm.debt_payments;

CREATE OR REPLACE VIEW public.crm_debts AS
SELECT * FROM crm.debts;

CREATE OR REPLACE VIEW public.crm_expense_templates AS
SELECT * FROM crm.expense_templates;

CREATE OR REPLACE VIEW public.crm_expenses AS
SELECT * FROM crm.expenses;

CREATE OR REPLACE VIEW public.crm_financial_accounts AS
SELECT * FROM crm.financial_accounts;

CREATE OR REPLACE VIEW public.crm_sales AS
SELECT * FROM crm.sales;

CREATE OR REPLACE VIEW public.crm_vehicles AS
SELECT * FROM crm.vehicles;

CREATE OR REPLACE VIEW public.safe_profiles AS
SELECT
    id,
    email,
    COALESCE(raw_user_meta_data ->> 'full_name', '') AS full_name
FROM auth.users;

CREATE OR REPLACE VIEW public.public_profiles AS
SELECT
    id,
    email,
    COALESCE(raw_user_meta_data ->> 'full_name', '') AS full_name
FROM auth.users;

GRANT SELECT ON public.safe_profiles TO authenticated;
GRANT SELECT ON public.public_profiles TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_server_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.server_updated_at = now();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION crm.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION crm.sync_expense_description()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF COALESCE(NULLIF(btrim(NEW.expense_description), ''), '') = '' THEN
        NEW.expense_description = NEW.description;
    END IF;

    IF COALESCE(NULLIF(btrim(NEW.description), ''), '') = '' THEN
        NEW.description = NEW.expense_description;
    END IF;

    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION crm.sync_sales_amount()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.amount IS NULL AND NEW.sale_price IS NOT NULL THEN
        NEW.amount = NEW.sale_price;
    END IF;

    IF NEW.sale_price IS NULL AND NEW.amount IS NOT NULL THEN
        NEW.sale_price = NEW.amount;
    END IF;

    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.crm_can_access(p_dealer_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path TO public, auth, pg_temp
AS $function$
DECLARE
    v_uid uuid := auth.uid();
BEGIN
    IF v_uid IS NULL OR p_dealer_id IS NULL THEN
        RETURN false;
    END IF;

    RETURN EXISTS (
        SELECT 1
        FROM public.organizations o
        WHERE o.id = p_dealer_id
          AND (
              o.owner_id = v_uid
              OR EXISTS (
                  SELECT 1
                  FROM public.dealer_team_members dtm
                  WHERE dtm.organization_id = o.id
                    AND dtm.user_id = v_uid
                    AND dtm.status = 'active'
              )
          )
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_my_role(_org_id uuid)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path TO public, auth, pg_temp
AS $function$
DECLARE
    v_uid uuid := auth.uid();
    v_role text;
BEGIN
    IF v_uid IS NULL OR _org_id IS NULL THEN
        RETURN NULL;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.organizations
        WHERE id = _org_id
          AND owner_id = v_uid
    ) THEN
        RETURN 'owner';
    END IF;

    SELECT dtm.role::text
    INTO v_role
    FROM public.dealer_team_members dtm
    WHERE dtm.organization_id = _org_id
      AND dtm.user_id = v_uid
      AND dtm.status = 'active'
    ORDER BY dtm.created_at ASC
    LIMIT 1;

    RETURN v_role;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_my_permissions(_org_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path TO public, auth, pg_temp
AS $function$
DECLARE
    v_uid uuid := auth.uid();
    v_permissions jsonb;
BEGIN
    IF v_uid IS NULL OR _org_id IS NULL THEN
        RETURN '{}'::jsonb;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.organizations
        WHERE id = _org_id
          AND owner_id = v_uid
    ) THEN
        RETURN jsonb_build_object('all', true);
    END IF;

    SELECT COALESCE(dtm.permissions, '{}'::jsonb)
    INTO v_permissions
    FROM public.dealer_team_members dtm
    WHERE dtm.organization_id = _org_id
      AND dtm.user_id = v_uid
      AND dtm.status = 'active'
    ORDER BY dtm.created_at ASC
    LIMIT 1;

    RETURN COALESCE(v_permissions, '{}'::jsonb);
END;
$function$;

CREATE OR REPLACE FUNCTION public.add_sync_columns(schema_name text, table_name text)
RETURNS void
LANGUAGE plpgsql
SET search_path TO public, pg_temp
AS $function$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = schema_name
          AND table_name = table_name
    ) THEN
        EXECUTE format(
            'ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS server_updated_at timestamptz NOT NULL DEFAULT now()',
            schema_name,
            table_name
        );
        EXECUTE format(
            'ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS last_modified_by uuid',
            schema_name,
            table_name
        );
    END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_admin_dashboard_stats()
RETURNS json
LANGUAGE sql
SET search_path TO public, pg_temp
AS $function$
    SELECT '{}'::json;
$function$;

CREATE OR REPLACE FUNCTION public.get_users_for_admin(
    p_limit integer DEFAULT 50,
    p_offset integer DEFAULT 0,
    p_search text DEFAULT NULL,
    p_status_filter text DEFAULT NULL,
    p_sort_by text DEFAULT 'created_at',
    p_sort_order text DEFAULT 'desc'
)
RETURNS TABLE(
    user_id uuid,
    email text,
    full_name text,
    phone text,
    location text,
    is_dealer boolean,
    verification_status text,
    created_at timestamptz,
    last_sign_in_at timestamptz,
    email_confirmed_at timestamptz,
    banned_until timestamptz,
    deleted_at timestamptz,
    listings_count integer,
    messages_count integer,
    account_status text,
    total_count integer
)
LANGUAGE sql
SET search_path TO public, pg_temp
AS $function$
    SELECT
        NULL::uuid,
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::boolean,
        NULL::text,
        NULL::timestamptz,
        NULL::timestamptz,
        NULL::timestamptz,
        NULL::timestamptz,
        NULL::timestamptz,
        NULL::integer,
        NULL::integer,
        NULL::text,
        0::integer
    WHERE false;
$function$;

CREATE OR REPLACE FUNCTION public.admin_get_user_details(p_user_id uuid)
RETURNS jsonb
LANGUAGE sql
SET search_path TO public, pg_temp
AS $function$
    SELECT jsonb_build_object('userId', p_user_id);
$function$;

CREATE OR REPLACE FUNCTION public.admin_update_user_profile_with_log(
    p_user_id uuid,
    p_admin_user_id uuid,
    p_full_name text DEFAULT NULL,
    p_phone text DEFAULT NULL,
    p_location text DEFAULT NULL,
    p_verification_status text DEFAULT NULL,
    p_is_dealer boolean DEFAULT NULL
)
RETURNS jsonb
LANGUAGE sql
SET search_path TO public, pg_temp
AS $function$
    SELECT jsonb_build_object('success', true, 'userId', p_user_id, 'adminUserId', p_admin_user_id);
$function$;

CREATE OR REPLACE FUNCTION public.admin_suspend_user_with_log(
    p_user_id uuid,
    p_admin_user_id uuid,
    p_suspend boolean,
    p_duration_hours integer DEFAULT 24,
    p_reason text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE sql
SET search_path TO public, pg_temp
AS $function$
    SELECT jsonb_build_object('success', true, 'userId', p_user_id, 'adminUserId', p_admin_user_id, 'suspend', p_suspend);
$function$;

CREATE OR REPLACE FUNCTION public.get_user_activity_logs(
    p_user_id uuid,
    p_limit integer DEFAULT 50,
    p_offset integer DEFAULT 0
)
RETURNS TABLE(
    id uuid,
    action text,
    details jsonb,
    admin_username text,
    ip_address inet,
    user_agent text,
    created_at timestamptz
)
LANGUAGE sql
SET search_path TO public, pg_temp
AS $function$
    SELECT
        NULL::uuid,
        NULL::text,
        NULL::jsonb,
        NULL::text,
        NULL::inet,
        NULL::text,
        NULL::timestamptz
    WHERE false;
$function$;

CREATE OR REPLACE FUNCTION public.admin_bulk_suspend_users(
    p_user_ids uuid[],
    p_admin_user_id uuid,
    p_suspend boolean,
    p_duration_hours integer DEFAULT 24,
    p_reason text DEFAULT NULL
)
RETURNS json
LANGUAGE sql
SET search_path TO public, pg_temp
AS $function$
    SELECT '{}'::json;
$function$;

CREATE OR REPLACE FUNCTION public.admin_bulk_update_verification(
    p_user_ids uuid[],
    p_admin_user_id uuid,
    p_verification_status text,
    p_reason text DEFAULT NULL
)
RETURNS json
LANGUAGE sql
SET search_path TO public, pg_temp
AS $function$
    SELECT '{}'::json;
$function$;

CREATE OR REPLACE FUNCTION public.admin_export_users_data(
    p_user_ids uuid[],
    p_include_activity_logs boolean DEFAULT false
)
RETURNS json
LANGUAGE sql
SET search_path TO public, pg_temp
AS $function$
    SELECT '{}'::json;
$function$;

CREATE OR REPLACE FUNCTION public.get_listings_for_admin(
    p_limit integer DEFAULT 50,
    p_offset integer DEFAULT 0,
    p_search text DEFAULT NULL,
    p_status_filter text DEFAULT NULL,
    p_sort_by text DEFAULT 'created_at',
    p_sort_order text DEFAULT 'desc'
)
RETURNS TABLE(
    id uuid,
    title text,
    make text,
    model text,
    year integer,
    price integer,
    status text,
    moderation_status text,
    user_name text,
    user_email text,
    views integer,
    created_at timestamptz,
    updated_at timestamptz,
    total_count integer
)
LANGUAGE sql
SET search_path TO public, pg_temp
AS $function$
    SELECT
        NULL::uuid,
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::integer,
        NULL::integer,
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::integer,
        NULL::timestamptz,
        NULL::timestamptz,
        0::integer
    WHERE false;
$function$;

CREATE OR REPLACE FUNCTION public.get_messages_for_admin(
    p_limit integer DEFAULT 50,
    p_offset integer DEFAULT 0,
    p_search text DEFAULT NULL
)
RETURNS TABLE(
    id uuid,
    content text,
    sender_name text,
    sender_email text,
    receiver_name text,
    receiver_email text,
    listing_title text,
    listing_id uuid,
    is_read boolean,
    created_at timestamptz,
    total_count integer
)
LANGUAGE sql
SET search_path TO public, pg_temp
AS $function$
    SELECT
        NULL::uuid,
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::uuid,
        NULL::boolean,
        NULL::timestamptz,
        0::integer
    WHERE false;
$function$;

CREATE OR REPLACE FUNCTION public.admin_delete_listing(
    p_listing_id uuid,
    p_admin_user_id uuid,
    p_reason text
)
RETURNS jsonb
LANGUAGE sql
SET search_path TO public, pg_temp
AS $function$
    SELECT jsonb_build_object('success', false, 'listingId', p_listing_id, 'adminUserId', p_admin_user_id, 'reason', p_reason);
$function$;

CREATE OR REPLACE FUNCTION public.delete_user_account(user_id uuid)
RETURNS void
LANGUAGE plpgsql
SET search_path TO public, pg_temp
AS $function$
BEGIN
    RETURN;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.crm_can_access(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_role(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_permissions(uuid) TO authenticated;
