name: Supabase DB Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  db-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 2.72.7

      - name: Reset Supabase CLI temp state
        run: rm -rf supabase/.temp supabase/supabase

      - name: Start Supabase DB
        run: supabase db start

      - name: Run pgTAP
        run: supabase test db supabase/tests/database
